config/routes.rb
Hcs::Application.routes.draw do
 
   get "welcome/index"
  root "welcome#index"
   resources :users
   resources :units
   resources :tasks
   resources :students
   resources :contacts
   resources :datafiles
end

app/models/datafile.rb
class Datafile < ActiveRecord::Base
     has_attached_file :dfile
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/unit.rb
class Unit < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
     has_many :taskfiles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/datafiles_controller.rb
class DatafilesController < ApplicationController

   def new
      @datafile = Datafile.new
   end
   def create
      uploaded_io = params[:datafile][:dfile]
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
          file.write(uploaded_io.read)
          end
   end
   def index
      @datafiles = Datafile.all
   end
   def upload
      uploaded_io = params[:datafile][:dfile]
      File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
      file.write(uploaded_io.read)
   end
   private
      def datafile_params
          params.require(:datafile).permit(:name, :comment, :time, :size)
      end
end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
   def new
      @student = Student.new
   end
   def index
      @students = Student.all
   end
   def create
      @student = Student.new(student_params)

      if @student.save
          redirect_to @student
      else
          render 'new'
      end
   end
   def edit
      @student = Student.find(params[:id])
   end
   def destroy
       @student = Student.find(params[:id])
       @student.destroy

       redirect_to students_path
   end
   def update
       @student = Student.find(params[:id])
 
       if @student.update(student_params)
           redirect_to @student
       else
           render 'edit'
       end
   end
   private
      def student_params
          params.require(:student).permit(:surname, :name, :phone, :h1t1, :h1t2, :h1t3, :h2t1, :h3t1, :h3t2)
      end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
   def new
      @task = Task.new
   end
   def index
      @tasks = Task.all
   end
   def create
      @task = Task.new(task_params)

      if @task.save
          redirect_to @task
      else
          render 'new'
      end
   end
   def edit
      @task = Task.find(params[:id])
   end
   def destroy
       @task = Task.find(params[:id])
       @task.destroy

       redirect_to tasks_path
   end
   def update
       @task = Task.find(params[:id])
 
       if @task.update(task_params)
           redirect_to @task
       else
           render 'edit'
       end
   end
   private
      def task_params
          params.require(:task).permit(:number, :homework, :condition, :time)
      end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
   def new
      @unit = Unit.new
   end
   def index
      @units = Unit.all
   end
   def create
      @unit = Unit.new(unit_params)

      if @unit.save
          redirect_to @unit
      else
          render 'new'
      end
   end
   def edit
      @unit = Unit.find(params[:id])
   end
   def destroy
       @unit = Unit.find(params[:id])
       @unit.destroy
       system "rake environment tire:import CLASS=Unit FORCE=true"
       redirect_to units_path
   end
   def update
       @unit = Unit.find(params[:id])
 
       if @unit.update(unit_params)
           redirect_to @unit
       else
           render 'edit'
       end
   end
   private
      def unit_params
          params.require(:unit).permit(:surname, :state, :homework, :number, :comment, :time)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
      @user = User.new
   end
   def index
      @users = User.all
   end
   def create
      @user = User.new(user_params)

      if @user.save
          redirect_to @user
      else
          render 'new'
      end
   end
   def edit
      @user = User.find(params[:id])
   end
   def destroy
       @user = User.find(params[:id])
       @user.destroy

       redirect_to users_path
   end
   def update
       @user = User.find(params[:id])
 
       if @user.update(user_params)
           redirect_to @user
       else
           render 'edit'
       end
   end
   private
      def user_params
          params.require(:user).permit(:surname, :name, :patronymic, :phone, :email)
      end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @users = User.all
        @tasks = Task.all
        @datafile = Datafile.new
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datafiles_helper.rb
module DatafilesHelper
end

app/helpers/taskfiles_helper.rb
module TaskfilesHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hcs</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |s| %>
  <p>
    <%= s.label :surname %><br>
    <%= s.text_field :surname %>
  </p>
  <p>
    <%= s.label :name %><br>
    <%= s.text_field :name %>
  </p>
  <p>
    <%= s.label :telephone %><br>
    <%= s.text_field :phone %>
  </p>
  <p>
    <%= s.label :hw1t1 %><br>
    <%= s.text_field :h1t1 %>
  </p>
  <p>
    <%= s.label :hw1t2 %><br>
    <%= s.text_field :h1t2 %>
  </p>
  <p>
    <%= s.label :hw1t3 %><br>
    <%= s.text_field :h1t3 %>
  </p>
  <p>
    <%= s.label :hw2t1 %><br>
    <%= s.text_field :h2t1 %>
  </p>
  <p>
    <%= s.label :hw3t1 %><br>
    <%= s.text_field :h3t1 %>
  </p>
  <p>
    <%= s.label :hw3t2 %><br>
    <%= s.text_field :h3t2 %>
  </p>
 
  <p>
    <%= s.submit %>
  </p>
<% end %>

app/views/students/edit.html.erb
<h1>Edit student information</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<h1>Students</h1>
<table border="1">
  <tr>
    <th>Surname</th>
    <th>Name</th>
    <th>1.1</th>
    <th>1.2</th>
    <th>1.3</th>
    <th>2.1</th>
    <th>3.1</th>
    <th>3.2</th>
  </tr>
 
<% @students.each do |s| %>
  <tr>
    <td><%= s.surname%></td>
    <td><%= s.name %></td>
    <td><%= s.h1t1 %></td>
    <td><%= s.h1t2 %></td>
    <td><%= s.h1t3 %></td>
    <td><%= s.h2t1 %></td>
    <td><%= s.h3t1 %></td>
    <td><%= s.h3t2 %></td>
    <td><%= link_to 'Edit', edit_student_path(s) %></td>
    <td><%= link_to 'Destroy', student_path(s),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/students/new.html.erb
<h1>Add student</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', students_path %>

app/views/students/table.erb
<table>
   <tr>
       <th>Student</th>
       <th>1.1</th>
       <th>1.2</th>
       <th>1.3</th>
       <th>2.1</th>
       <th>3.1</th>
       <th>3.2</th>
   </tr>
<% @students.each do |student| %>
   <tr>
       <td><%= student.surname %></td>
       <td><%= student.h1t1 %></td>
       <td><%= student.h1t2 %></td>
       <td><%= student.h1t3 %></td>
       <td><%= student.h2t1 %></td>
       <td><%= student.h3t1 %></td>
       <td><%= student.h3t2 %></td>
   </tr>
<% end %>
</table>

app/views/tasks/_taskForm.html.erb
<%= form_for @task do |s| %>
  <p>
    <%= s.label :number %><br>
    <%= s.text_field :number %>
  </p>
  <p>
    <%= s.label :homework %><br>
    <%= s.text_field :homework %>
  </p>
  <p>
    <%= s.label :condition %><br>
    <%= s.text_field :condition %>
  </p>
  <p>
    <%= s.label :date %><br>
    <%= s.text_field :time %>
  </p>
  <p>
    <%= s.submit %>
  </p>
<% end %>

number:float homework:float condition:text time:date

app/views/tasks/edit.html.erb
<h1>Edit tasks information</h1>
 
<%= render 'taskForm' %>
 
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>tasks</h1>
<table border="1">
  <tr>
    <th>Homework</th>
    <th>Number</th>
    <th>Time</th>
    <th>Condition</th>
  </tr>
 
<% @tasks.each do |s| %>
  <tr>
    <td><%= s.homework%></td>
    <td><%= s.number %></td>
    <td><%= s.time %></td>
    <td><%= s.condition %></td>
    <td><%= link_to 'Edit', edit_task_path(s) %></td>
    <td><%= link_to 'Destroy', task_path(s),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/tasks/new.html.erb
<h1>Add task</h1>
 
<%= render 'taskForm' %>
 
<%= link_to 'Back', tasks_path %>

app/views/units/_unitForm.html.erb
<%= form_for @unit do |s| %>
  <p>
    <%= s.label :surname %><br>
    <%= s.text_field :surname %>
  </p>
  <p>
    <%= s.label :homework %><br>
    <%= s.text_field :homework %>
  </p>
  <p>
    <%= s.label :number %><br>
    <%= s.text_field :number %>
  </p>
  <p>
    <%= s.label :state %><br>
    <%= s.text_field :state %>
  </p>
  <p>
    <%= s.label :comment %><br>
    <%= s.text_field :comment %>
  </p>
  <p>
    <%= s.submit %>
  </p>
<% end %>

app/views/units/edit.html.erb
<h1>Edit hometasks info</h1>
 
<%= render 'unitForm' %>
 
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Studentsefrecv</h1>
<table border="1">
  <tr>
    <th>Surname</th>
    <th>Homework</th>
    <th>Number</th>
    <th>State</th>
    <th>Comment</th>
    <th>Date</th>
  </tr>
 
<% @units.each do |s| %>
  <tr>
    <td><%= s.surname%></td>
    <td><%= s.homework %></td>
    <td><%= s.number %></td>
    <td><%= s.state %></td>
    <td><%= s.comment %></td>
    <td><%= link_to 'Edit', edit_unit_path(s) %></td>
    <td><%= link_to 'Destroy', unit_path(s),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/units/new.html.erb
<h1>Add student</h1>
 
<%= render 'unitForm' %>
 
<%= link_to 'Back', units_path %>

app/views/users/_userForm.html.erb
<%= form_for @user do |s| %>
  <p>
    <%= s.label :surname %><br>
    <%= s.text_field :surname %>
  </p>
  <p>
    <%= s.label :name %><br>
    <%= s.text_field :name %>
  </p>
  <p>
    <%= s.label :patronymic %><br>
    <%= s.text_field :patronymic %>
  </p>
  <p>
    <%= s.label :telephone %><br>
    <%= s.text_field :phone %>
  </p>
  <p>
    <%= s.label :email %><br>
    <%= s.text_field :email %>
  </p>
  <p>
    <%= s.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user information</h1>
 
<%= render 'userForm' %>
 
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Students</h1>
<table border="1">
  <tr>
    <th>Surname</th>
    <th>Name</th>
    <th>Patronymic</th>
    <th>Phone</th>
    <th>Email</th>
  </tr>
 
<% @users.each do |s| %>
  <tr>
    <td><%= s.surname%></td>
    <td><%= s.name %></td>
    <td><%= s.patronymic %></td>
    <td><%= s.phone %></td>
    <td><%= s.email %></td>
    <td><%= link_to 'Edit', edit_student_path(s) %></td>
    <td><%= link_to 'Destroy', student_path(s),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1>Add student</h1>
 
<%= render 'userForm' %>
 
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hometask</h1>


<%=form_for @datafile, :html => {:multipart => true} do |s|%>

<div class="field">

<%=s.label :file %><br />

<%=s.file_field :dfile%>
<p><%= s.submit( 'upload' ) %></p>

  </div>

<% end %>

<%= link_to 'Add task', new_task_path %>

<table border="1">
<tr>
    <td>Surname</td>
    <td>Name</td>
    <td>Patronymic</td>
    <% @tasks.each do |s| %>
         <td><%= (s.homework + (s.number/10))%></td> 
    <% end %>
</tr>
<% @users.each do |s| %>
  <tr>
    <td><%= s.surname%></td>
    <td><%= s.name%></td>
    <td><%= s.patronymic%></td>

    <% @tasks.each do |t| %>
        <td><%= Unit.where(surname: s.surname, homework: t.homework, number: t.number).take.state %></td>
    <% end %>

      <td><%= link_to 'Edit', edit_user_path(s) %></td>
      <td><%= link_to 'Destroy', user_path(s),
                   method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>